/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Database.Database;
import static Forms.Utilities.SendSMS.PASSWORD;
import static Forms.Utilities.SendSMS.USER_NAME;
import static Forms.Utilities.SendSMS.sendFromGMail;

import Forms.Utilities.TextCheck;
import static Forms.Utilities.TextCheck.generateRandomString;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class frmKhoiPhucTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form frmKhoiPhucTaiKhoan
     */
    Database db=new Database();
    public frmKhoiPhucTaiKhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNotice1 = new javax.swing.JLabel();
        txtNotice2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        btnRestore = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(964, 465));

        txtNotice1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNotice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNotice1.setText("1 Hệ thống sẽ gửi tên đăng nhập và mật khẩu mới dưới dạng mail tới Email được nhập                      ");

        txtNotice2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNotice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNotice2.setText("2 Nếu không nhớ Email của mình hãy liên hệ quản lý của cửa hàng để cập nhật lại mật khẩu cho bạn");

        txtTitle.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("TRANG KHÔI PHỤC TÀI KHOẢN");

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtEmail.setText("Email:");

        edtEmail.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N

        btnRestore.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRestore.setText("Khôi phục");
        btnRestore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestoreMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Quay lại trang đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNotice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
            .addComponent(txtNotice2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRestore, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(edtEmail))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(txtNotice1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNotice2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestoreMouseClicked
        // TODO add your handling code here:
        if(TextCheck.isValidEmailAddress(new String(edtEmail.getText()))){
            //là email
            
            try {
                //query lấy thông tin tài khoản theo sms
                //chạy và kiểm tra xem tài khoản đăng nhập có tồn tại
                Statement st=db.con.createStatement();
                ResultSet rs = st.executeQuery("select a.MaNV,a.TK from taikhoan a, nguoidung b where b.Email='"+new String(edtEmail.getText()).toLowerCase()+"' and a.MaNV=b.MaNV");

                //dịch nút cho thông báo
                UIManager.put("OptionPane.okButtonText", "Đóng");

                //kiểm tra số dòng lấy được có phải =1 hay không
                if (!rs.next()) {
                    //RỖNG
                    JOptionPane.showMessageDialog(null,"Không có tài khoản nào được đăng ký với email trên","Lỗi không tìm thấy tài khoản", JOptionPane.ERROR_MESSAGE);

                } else {
                    //CÓ

                    String newTDN=rs.getString("TK"); //Lấy tên đăng nhập
                    String newMK=generateRandomString(5); //tạo mật khẩu mới
                    System.out.println(""+newMK);
                    //update taikhoan
                    Statement st_up=db.con.createStatement();
                    int  rows = st_up.executeUpdate("update taikhoan set MK='"+newMK+"' where MaNV='"+rs.getString("MaNV")+"' and TK='"+newTDN+"'");

                    if(rows==1){
                        //update thành công 
                        
                        //gửi mail
                        //THÔNG TIN GỬI MAIL
                        String[] to = { new String(edtEmail.getText()) }; // list of recipient email addresses
                        String subject = "Mật khẩu của bạn vừa được cập nhật";
                        String body = "Tên đăng nhập:"+newTDN+"\nMật khẩu mới:"+newMK;

                        sendFromGMail(USER_NAME, PASSWORD, to, subject, body); //HÀM GỬI MAIL
                        
                        JOptionPane.showMessageDialog(null,"Mail chứa thông tin đăng nhập đã được gửi thành công. Hãy kiểm tra hòm thư của bạn","Khôi phục thành công", JOptionPane.PLAIN_MESSAGE);
                    }else{
                        //ko update được
                        JOptionPane.showMessageDialog(null,"Không cập nhật được","Lỗi không cập nhật được tài khoản", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmKhoiPhucTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"lỗi"+ex,"SQLException", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            //dịch nút cho thông báo
            UIManager.put("OptionPane.cancelButtonText", "Đóng");
            UIManager.put("OptionPane.okButtonText", "Đóng");
            JOptionPane.showMessageDialog(null,"Lỗi nhập địa chỉ mail. Vd:name@gmail.com","Lỗi nhập email", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btnRestoreMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try{
            frmDangNhap f = new frmDangNhap();
            f.setVisible(true);
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKhoiPhucTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKhoiPhucTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKhoiPhucTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKhoiPhucTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmKhoiPhucTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRestore;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNotice1;
    private javax.swing.JLabel txtNotice2;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
